version: '3.8'

services:
  app:
    image: does_app:deploy
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: base
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 #n/b: In a strict rigor this is not necessary since the container already has this as the CMD
    expose:
      - 8000
    env_file:
      - ".envs/${ENV_NAME:-staging}.env"

  nginx:
    image: does_nginx:deploy
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        TARGET_TAG: deploy
    ports:
      - 80:80
    depends_on:
      - app